name: Trigger Render Deployment

on:
  workflow_run:
    workflows: ["Deployment pipeline"]
    types:
      - completed

jobs:
    deploy:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main' }}
  
      steps:
        - name: Debug info
          run: |
            echo "Event: ${{ github.event.workflow_run.event }}"
            echo "Head Branch: ${{ github.event.workflow_run.head_branch }}"
            echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
  
        - name: Trigger deployment
          uses: sws2apps/render-deployment@main
          with:
            serviceId: ${{ secrets.RENDER_SERVICE_ID }}
            apiKey: ${{ secrets.RENDER_API_KEY }}
            multipleDeployment: false
  