name: Trigger Render Deployment

on:
  workflow_run:
    workflows: ["Deployment pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && if: ${{ github.event_name == 'push' }} }}
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deployment
        uses: sws2apps/render-deployment@main
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false
