name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:

  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    outputs:
      commit_msg: ${{ steps.check_skip.outputs.commit_msg }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Check commit message
        id: check_skip
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B | tr -d '\n' | sed 's/%/%25/g; s/\r/%0D/g; s/\n/%0A/g')
          echo "commit_msg=$COMMIT_MSG" >> $GITHUB_OUTPUT
      - name: Directory content
        run : |
              ls -l
      - name: Install dependencies 
        run: npm install  
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: deploy
        if: ${{ github.event_name == 'push' && !contains(steps.check_skip.outputs.commit_msg, '#skip') }}
        uses: sws2apps/render-deployment@main
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && !contains(needs.simple_deployment_pipeline.outputs.commit_msg, '#skip') }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  notify_success:
    needs: [tag_release]
    if: ${{ success() && github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Notify Discord of success
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: | 
            Deployment successful for commit: ${{ github.sha }} by ${{ github.event.head_commit.author.name }}
            Live site: https://full-stack-open-pokedex-8mew.onrender.com
          

  notify_failure:
    needs: [simple_deployment_pipeline]
    if: ${{ failure() && github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    steps:
    - name: Notify Discord of failure
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: |
          Build failed!
          Commit: ${{ github.event.head_commit.url }}
          Message: ${{ github.event.head_commit.message }}
          Author: ${{ github.event.head_commit.author.name }}
            


          
      